name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
       - master
    paths-ignore:
      - '**.md'

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Build
        run: |
          # PairMesh
          for arch in "386" "amd64"
          do
            echo "Building $arch for Linux"
            GOARCH=$arch make pairmesh
          done
          
          # PairPortal/PairRelay
          make pairportal
          make pairrelay

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Build
        run: |
          # PairMesh
          for arch in "arm64" "amd64"
          do
            echo "Building $arch for MacOS"
            GOARCH=$arch make pairmesh
          done

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Build
        run: |
          go build -o bin/PairMesh.exe  -ldflags "-s -w -H=windowsgui -X github.com/pairmesh/pairmesh/version.GitHash=$(git describe --no-match --always --dirty) -X github.com/pairmesh/pairmesh/version.GitBranch=$(git rev-parse --abbrev-ref HEAD)" ./cmd/pairmesh

