name: Release
on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master

# OS and Arch reference: https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Build and Package
        run: build/linux_dist.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: |
            dist

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Build and Package
        run: build/macos_dist.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: |
            dist

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Build
        run: |
          go build -o dist/PairMesh.exe  -ldflags "-s -w -H=windowsgui -X github.com/pairmesh/pairmesh/version.GitHash=$(git describe --no-match --always --dirty) -X github.com/pairmesh/pairmesh/version.GitBranch=$(git rev-parse --abbrev-ref HEAD)" ./cmd/pairmesh
          tar -czf dist/"pairmesh_$(git describe --tags --abbrev=0)_windows_amd64.tar.gz" -C dist pairmesh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: |
            dist
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            distributions/*
