name: Unit Test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
       - master
    paths-ignore:
      - '**.md'

jobs:
  unit-test:
    name: Unit Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Unit Test
        run: make test
